%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
# image_width: 1241
# image_height: 376
image_width: 1224
image_height: 370
distortion_parameters:
   k1: 0
   k2: 0
   p1: 0
   p2: 0
projection_parameters:
   fx: 7.070493e+02
   fy: 7.070493e+02
   cx: 6.040814e+02
   cy: 1.805066e+02
