%YAML:1.0
---
model_type: PINHOLE
camera_name: camera
# image_width: 1241
# image_height: 376
image_width: 1242
image_height: 375
distortion_parameters:
   k1: 0
   k2: 0
   p1: 0
   p2: 0
projection_parameters:
   fx: 721.5377
   fy: 721.5377
   cx: 609.5593
   cy: 172.854
